# Generated by Django 3.2.4 on 2021-07-07 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210704_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
